apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-scratch
  labels:
    app: sample-scratch
    kind: sample
spec:
  template:
    spec:
      containers:
      - name: sample-scratch
        env:
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_SSM_PREFIX
            value: /dev/sample/
