# Build Stage
FROM golang:1.14.6-buster AS build

WORKDIR /src

COPY go.mod go.sum main.go ./

RUN env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o app

RUN useradd appuser

# Final stage for runtime
FROM scratch

COPY --from=build /src/app /app

COPY --from=build /etc/passwd /etc/passwd 

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENV AWS_REGION="us-east-1"

EXPOSE 8000

USER appuser

ENTRYPOINT ["/app"]