apiVersion: v1
kind: Pod
metadata:
  name: sample-runtime
  namespace: default
  labels:
    app: sample-scratch
    kind: sample
spec:
  containers:
  - name: sample-runtime
    image: alfianabdi/sample:v0.3-multistage-runtime
    ports:
      - containerPort: 8000
    resources:
      limits:
        memory: 20Mi
      requests: 
        memory: 20Mi
    env:
      - name: AWS_REGION
        value: ap-southeast-1
  restartPolicy: Always
  dnsPolicy: ClusterFirst