apiVersion: v1
kind: Pod
metadata:
  name: sample-scratch
  namespace: default
  labels:
    app: sample-scratch
    kind: sample
spec:
  containers:
  - name: sample-scratch
    image: alfianabdi/sample:v0.3-multistage-scratch
    env:
      - name: AWS_REGION
        value: ap-southeast-1
    ports:
      - containerPort: 8000
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 20Mi
  restartPolicy: Always
  dnsPolicy: ClusterFirst